name: fitman_backend
description: Фитнес-менеджер Backend API
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  dart_frog: ^1.2.4
  postgres: ^3.5.8
  dart_jsonwebtoken: ^3.1.1
  bcrypt: ^1.1.3
  dotenv: ^4.2.0

dev_dependencies:
  dart_frog_gen: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3